Repository joyent/conch-shell, pull requests merged in 2018-09, with the labels that each got.

#159 add library and command support for the new /hardware_vendor endpoints
  pkg/commands/internal/hardware/init.go
  pkg/commands/internal/hardware/vendor.go
  pkg/conch/hardware_vendor.go
  pkg/conch/hardware_vendor_test.go
Labels: enhancement

#161 when loading the config file from json with or without a path, always use New() so we get sane defaults
  cmd/conch/conch.go
  pkg/config/main.go
Labels: bug

#162 support rack serial numbers and asset tags in the library and "global" commands
  pkg/commands/internal/global/rack.go
  pkg/conch/devices.go
  pkg/conch/global_datacenter.go
  pkg/conch/global_datacenter_rack.go
Labels: enhancement

#163 remove workspace validation states
  Gopkg.lock
  Gopkg.toml
  pkg/commands/internal/validation/init.go
  pkg/commands/internal/validation/state.go
  pkg/conch/conch_test.go
  pkg/conch/fixtures/get_validation_plan.yaml
  pkg/conch/fixtures/get_validation_plans.yaml
  pkg/conch/fixtures/get_validations.yaml
  pkg/conch/fixtures/run_validation.yaml
  pkg/conch/fixtures/run_validation_plan.yaml
  pkg/conch/validations_test.go
Labels: enhancement

#171 remove device roles and servies as per joyent/conch#423
  pkg/commands/internal/devices/init.go
  pkg/commands/internal/devices/roles.go
  pkg/commands/internal/devices/services.go
  pkg/commands/internal/workspaces/failure.go
  pkg/conch/devices.go
  pkg/conch/devices_test.go
  pkg/util/magic_ids.go
Labels: breaking

#172 when rendering a Rack as JSON, if the Slots element is null, do not render it
  pkg/conch/devices.go
Labels: wat

#173 add the ability for admins to list all users in the system, via `admin users`
  pkg/commands/internal/admin/init.go
  pkg/commands/internal/admin/main.go
  pkg/conch/user.go
  pkg/conch/user_test.go
  pkg/conch/workspaces.go
Labels: enhancement

#174 adding vendor_name to location
  pkg/conch/devices.go
Labels: enhancement
