Repository joyent/conch-shell, pull requests merged in 2018-04, with the labels that each got.

#46 Fix #45 by writing the new Session data out to the config every time we verify login credentials
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/commands/internal/profile/profile.go
  pkg/util/util.go
Labels: bug

#47 build: make app version match upcoming git tag
  Makefile
Labels: build

#48 build: add a release target for freebsd-amd64
  Makefile
Labels: build

#51 build: conch-mbo is broken for solaris/smartos right now so let's not try to build it.
  Makefile
Labels: build

#53 Improve the Makefile, including a new 'check' target that runs gometalinter
  .travis.yml
  Makefile
  README.md
Labels: build

#54 build: by request, add an openbsd-amd64 build
  Makefile
Labels: build, enhancement

#55 build: sigh. modify travis.yml to actually keep the new bsd builds
  .travis.yml
Labels: bug, build

#57 build: enable golint in make check
  Makefile
  pkg/util/util.go
Labels: build

#60 Support device roles and services
  Gopkg.lock
  Gopkg.toml
  pkg/commands/internal/devices/init.go
  pkg/commands/internal/devices/roles.go
  pkg/commands/internal/devices/services.go
  pkg/commands/internal/workspaces/failure.go
  pkg/util/util.go
Labels: enhancement

#58 feat: Commands to manage Validations and Validation Plans
  pkg/commands/init.go
  pkg/commands/internal/validation/init.go
  pkg/commands/internal/validation/plan.go
  pkg/commands/internal/validation/state.go
  pkg/commands/internal/validation/validation.go
  pkg/util/util.go
Labels: enhancement

#61 fix: bump shell internal version to 0.3.1
  Makefile
Labels: bug

#65 BREAKING: bring in go-conch v2, which removed pgtime
  Gopkg.lock
  Gopkg.toml
  pkg/commands/internal/workspaces/failure.go
  pkg/commands/internal/workspaces/workspaces.go
  pkg/util/util.go
Labels: breaking

#69 feat: add validation results to validation state table
  pkg/commands/internal/validation/init.go
  pkg/commands/internal/validation/state.go
Labels: enhancement

#70 feat: add command to render device report
  pkg/commands/internal/devices/devices.go
  pkg/commands/internal/devices/init.go
Labels: enhancement
