Repository joyent/conch-shell, pull requests merged in 2018-05, with the labels that each got.

#77 feat: convert the epoch time in BuildTime to a human readable string in our standard output format
  cmd/conch/conch.go
Labels: enhancement

#78 feat: when building the GitRev, specify --long so we always get the current revision hash
  Makefile
Labels: build, enhancement

#79 feat: until the future of orchestration is decided, do not include the orc commands
  pkg/commands/init.go
  pkg/commands/internal/orc/init.go
  pkg/commands/internal/orc/lifecycles.go
  pkg/commands/internal/orc/steps.go
  pkg/commands/internal/orc/workflows.go
Labels: enhancement

#80 feat: add the ability to self-update to the latest release, and the ability to view the current changelog
  Makefile
  cmd/conch/conch.go
  pkg/commands/init.go
  pkg/commands/internal/update/init.go
  pkg/commands/internal/update/main.go
  pkg/util/util.go
Labels: build, enhancement

#81 Remove conch-mbo and the related code
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/conch-mbo/.keep
  cmd/conch-mbo/conch-mbo.go
  cmd/conch/conch.go
  pkg/reports/mbo/main.go
  pkg/templates/mbo_graphs.go
  pkg/util/util.go
Labels: breaking

#82 docs: document in the README that one can override where go looks for SSL certs
  README.md
Labels: docs

#84 BREAKING: remove orchestration. Fixes #83
  cmd/conch/conch.go
  pkg/commands/init.go
  pkg/commands/internal/orc/init.go
  pkg/commands/internal/orc/lifecycles.go
  pkg/commands/internal/orc/steps.go
  pkg/commands/internal/orc/workflows.go
  pkg/util/util.go
Labels: breaking

#88 build: remove travis deploy block
  .travis.yml
Labels: build

#89 Support JWT Auth
  Gopkg.lock
  Gopkg.toml
  pkg/commands/init.go
  pkg/commands/internal/admin/init.go
  pkg/commands/internal/admin/main.go
  pkg/commands/internal/profile/init.go
  pkg/commands/internal/profile/profile.go
  pkg/config/main.go
  pkg/util/util.go
Labels: breaking, enhancement

#91 Use the canonical package name for mow.cli
  Gopkg.lock
  Gopkg.toml
  cmd/conch/conch.go
  pkg/commands/init.go
  pkg/commands/internal/admin/init.go
  pkg/commands/internal/admin/main.go
  pkg/commands/internal/devices/devices.go
  pkg/commands/internal/devices/init.go
  pkg/commands/internal/devices/roles.go
  pkg/commands/internal/devices/services.go
  pkg/commands/internal/hardware/hardware.go
  pkg/commands/internal/hardware/init.go
  pkg/commands/internal/profile/init.go
  pkg/commands/internal/profile/profile.go
  pkg/commands/internal/relay/init.go
  pkg/commands/internal/relay/main.go
  pkg/commands/internal/update/init.go
  pkg/commands/internal/update/main.go
  pkg/commands/internal/user/init.go
  pkg/commands/internal/user/user.go
  pkg/commands/internal/validation/init.go
  pkg/commands/internal/validation/plan.go
  pkg/commands/internal/validation/state.go
  pkg/commands/internal/validation/validation.go
  pkg/commands/internal/workspaces/create.go
  pkg/commands/internal/workspaces/failure.go
  pkg/commands/internal/workspaces/health.go
  pkg/commands/internal/workspaces/init.go
  pkg/commands/internal/workspaces/invite.go
  pkg/commands/internal/workspaces/workspaces.go
  pkg/util/util.go
Labels: build
